name: Clone and Build Repository
on: #TRIGGERS
    push: # On  push
        branches: #on brnaches
            - main # main one

jobs:
    BuildJob:
        runs-on: ubuntu-latest # Operating system selection
        env: # Environment can be controlled at the job or step level
            TERM: dumb #no prints
        steps:
            - name: Clone Repo with Checkout # first step
              uses: actions/checkout@v2 # clones repo! Action implemented in this repository, tag "2"
            - name: Install JDK
              uses: joschi/setup-jdk@v2.3.0 # download jdk! Action implemented in repository "joschi/setup-jdk" tag "2.3.0"
              with: # Actions parameters (action name omitted)
                java-version: 15
            - name: Build and Check :P #cusom action
              run: ./gradlew clean build #performs gradlew build, it check if present checkstyle, it runs test with junit, it assembles the jar
            - name: Send custom Telegram Message with args
              uses: appleboy/telegram-action@master
              with:
                to: ${{ secrets.TELEGRAM_TO }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                args: CI COMPLETED for ${{ github.event_name }} event on github.com/${{ github.repository }}, by ${{ github.actor }}.
                disable_web_page_preview: true
