name: telegram message
on: #TRIGGERS
    push: # On  push
        brancehs: #on brnaches
            - main # main one

jobs:
  Build:
    name: TelegramJob
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: The ${{ github.event_name }} event triggered, by ${{ github.actor }}.
